name: CI & CD
on:
    push:
        branches:
            - main
jobs:
    Build-and-Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 14
            - name: Install & build
              run: npm install && npm run generate2
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  publish_dir: ./docs
                  # cname: ideapp.dev
                  deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                  force_orphan: true
                  user_name: 'github-actions[bot]'
                  user_email: 'github-actions[bot]@users.noreply.github.com'