name: CI & CD
on:
    push:
        branches:
            - main
jobs:
    Build-and-Deploy:
        # see https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment
        environment:
            name: github-pages
            url: https://AmmanVMS.github.io/event-poster-generator
        # after using the environment, we need to make the secrets available
        # see https://docs.github.com/en/actions/security-guides/encrypted-secrets#example-using-bash
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: set version
              run: echo "{\"version\":\"`git log -1 --format=%cd --date=short`\"}" > version.json

            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 18

            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                path: ~/.npm
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                  ${{ runner.os }}-node-

            - name: Install & build
              run: npm install && npm run generate2

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  publish_dir: ./docs
                  # cname: ideapp.dev
                  deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                  force_orphan: true
                  user_name: 'github-actions[bot]'
                  user_email: 'github-actions[bot]@users.noreply.github.com'
